### ISSUE TITLE
Installation error and run error

### ISSUE THREAD

**Issue by lmordek** [iteratec/OpenSpeedMonitor#25]
Hello there,

I checked out the newest version and I treid to compile it under Debain and Windows 10 / Windows 2012 Server, but I get on all the OSs the same errors (see below), but it says that the build was successful. Then I treid the next command './gradlew prod bootRun', but I received there also an error (look at the end). Could somebody help me?

./gradlew assemble
...
Processing File 205 of 263 - spring-security-ui.css
Error Processing GString Template Engine groovy.lang.MissingPropertyException: No such property: grails for class: groovy.lang.Binding
Error Processing GString Template Engine
groovy.lang.MissingPropertyException: No such property: grails for class: groovy.lang.Binding
        at groovy.lang.Binding.getVariable(Binding.java:58)
        at groovy.lang.Binding.getProperty(Binding.java:105)
        at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:172)
        at groovy.lang.Closure.getPropertyTryThese(Closure.java:324)
        at groovy.lang.Closure.getPropertyDelegateFirst(Closure.java:314)
        at groovy.lang.Closure.getProperty(Closure.java:299)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
        at groovy.tmp.templates.GStringTemplateScript1$_getTemplate_closure1.doCall(GStringTemplateScript1.groovy:2)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure$WritableClosure.writeTo(Closure.java:856)
        at groovy.lang.Closure$WritableClosure.toString(Closure.java:982)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at asset.pipeline.DirectiveProcessor.directiveArgumentsFromGString(DirectiveProcessor.groovy:183)
        at asset.pipeline.DirectiveProcessor.findDirectives(DirectiveProcessor.groovy:167)
        at asset.pipeline.DirectiveProcessor.getDependencyTree(DirectiveProcessor.groovy:141)
        at sun.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
        at asset.pipeline.DirectiveProcessor.requireFileDirective(DirectiveProcessor.groovy:273)
        at asset.pipeline.DirectiveProcessor$requireFileDirective$0.callCurrent(Unknown Source)
        at asset.pipeline.DirectiveProcessor.requireFileDirective(DirectiveProcessor.groovy:278)
        at sun.reflect.GeneratedMethodAccessor221.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnCurrentN(ScriptBytecodeAdapter.java:82)
        at asset.pipeline.DirectiveProcessor.callDirective(DirectiveProcessor.groovy:192)
        at asset.pipeline.DirectiveProcessor.findDirectives(DirectiveProcessor.groovy:171)
        at asset.pipeline.DirectiveProcessor.getDependencyTree(DirectiveProcessor.groovy:141)
        at asset.pipeline.DirectiveProcessor.compile(DirectiveProcessor.groovy:65)
        at asset.pipeline.DirectiveProcessor$compile.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at asset.pipeline.DirectiveProcessor$compile.call(Unknown Source)
        at asset.pipeline.AssetCompiler$_compile_closure3.doCall(AssetCompiler.groovy:159)
        at sun.reflect.GeneratedMethodAccessor205.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at groovy.lang.Closure.call(Closure.java:426)
        at groovy.lang.Closure.call(Closure.java:420)
        at groovy.lang.Closure.run(Closure.java:507)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Unable to Locate Asset: /e
Processing File 206 of 263 - spring-security-ui-auth.css

...

Processing File 244 of 263 - jquery-ui.css
Error Processing GString Template Engine groovy.lang.MissingPropertyException: No such property: grails for class: groovy.lang.Binding
Error Processing GString Template Engine
groovy.lang.MissingPropertyException: No such property: grails for class: groovy.lang.Binding
....
Unable to Locate Asset: /e
Processing File 245 of 263 - spring-security-ui.js
Error Processing GString Template Engine groovy.lang.MissingPropertyException: No such property: grails for class: groovy.lang.Binding
Error Processing GString Template Engine
groovy.lang.MissingPropertyException: No such property: grails for class: groovy.lang.Binding

---------

./gradlew prod bootRun

FAILURE: Build failed with an exception.

* What went wrong:
Task 'prod' not found in root project 'OpenSpeedMonitor'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 9.536 secs

**Comment by nilskuhn** [comment]
The first error occurs due to a bug within the used grails plugin `spring-security-ui`. The bug is already fixed but no release providing the fix is available at the moment :( 

The error message doesn't affect functionality of OpenSpeedMonitor (OSM) so far. You should be able to use assembled war file without any issues. If you are observing any errors in OSM please re-open this issue.

For the second error you are right. Instead of `./gradlew prod bootRun` it must be
```
./gradlew -Dgrails.env=prod bootRun
```
We will fix documentation.
