### ISSUE TITLE
OSM can not aggregate anymore

### ISSUE THREAD

**Issue by csiebert** [iteratec/OpenSpeedMonitor#40]
The osm does not show aggregation results anymore. This once worked fine (and older aggregations are still shown). But it seems that since we created a new csi configuration (copy one from an existing) an error was triggered and the aggregation does not work any longer.

Following error message occurs in the log:

[14.08.2018 07:18:30] [THREAD ID=quartzScheduler_Worker-8] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper : You have
an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near
'from customer_frustration this_)' at line 1
[14.08.2018 07:18:30] [THREAD ID=quartzScheduler_Worker-8] WARN  grails.app.services.de.iteratec.osm.measurement.environment.
wptserverproxy.ResultPersisterService : No customer satisfaction can be written for EventResult: id=null
                wptStatus=0
                medianValue=true
                numberOfWptRun=1
                cachedView=CACHED
                docCompleteIncomingBytes=448824
                docCompleteRequests=21
                docCompleteTimeInMillisecs=3588
                domTimeInMillisecs=null
                firstByteInMillisecs=369
                fullyLoadedIncomingBytes=569663
                fullyLoadedRequestCount=76
                fullyLoadedTimeInMillisecs=8459
                loadTimeInMillisecs=3588
                startRenderInMillisecs=1300
                customerSatisfactionInPercent=null
                speedIndex=1433
                downloadAttempts=null
                firstStatusUpdate=null
                lastStatusUpdate=Tue Aug 14 09:18:30 CEST 2018
                validationState=null
                jobResultDate=2018-08-14 09:18:27.0
                jobResultJobConfigId=59
: could not extract ResultSet
org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:80)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:91)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2066)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1863)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1839)
        at org.hibernate.loader.Loader.doQuery(Loader.java:910)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:355)
        at org.hibernate.loader.Loader.doList(Loader.java:2554)
        at org.hibernate.loader.Loader.doList(Loader.java:2540)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2370)
... 

We used OSM 4.5.1 when it first occured, now using 4.6.0 with still the same error (and WPT 12.17)

A check and fix would be appreciated.

**Comment by csiebert** [comment]
Yes, the Iatter.

**Comment by csiebert** [comment]
An additional information, that maybe could bring a quick fix for this:

We at last don't use the csi at all. That means, that we don't have associated any Job Group or Page with any of the csi configurations (3) in our system. It seems that, when the last csi configuration was copied, the process of copying went wrong.

Is there a way to completely delete an existing csi configuration, so the incomplete sql command would have no effect any more (- even an sql command would help)?
